### ISSUE TITLE
demo_tts.py missing packages & run.py KeyError

### ISSUE THREAD

**Issue by ahmedlila** [Rongjiehuang/FastDiff#14]
I was trying to run the repo on colab:

- Inference for text-to-speech synthesis
- Inference from wav file
using the commands given in the ReadMe file but I am facing some errors that I can not move forward with.

1. used the default TTS command `!python demo_tts.py` but it returns an error says 
`| models Trainable Parameters: 15.315M 07/21 02:09:50 PM NumExpr defaulting to 2 threads.
Traceback (most recent call last): File "/content/drive/MyDrive/FastDiff_main/FastDiff/tasks/base_task.py", line 39, in _get_data_loader value = getattr(self, attr_name) File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1208, in __getattr__
type(self).__name__, name))
AttributeError: 'FastDiffTask' object has no attribute '_lazy_test_dataloader'`
`File "/content/drive/MyDrive/FastDiff_main/FastDiff/data_gen/tts/vocoder_binarizer.py", line 18, in <module>
from vocoders.base_vocoder import get_vocoder_cls  
File "/content/drive/MyDrive/FastDiff_main/FastDiff/vocoders/__init__.py", line 1, in <module>
from vocoders import pwg
ImportError: cannot import name 'pwg' from 'vocoders' (/content/drive/MyDrive/FastDiff_main/FastDiff/vocoders/__init__.py)`
I searched for the origin of pwg but didn't find something related.

2. Inference from wav file using the following command `!python run --config=='modules/FastDiff/config/FastDiff.yaml'--exp_name $trial --infer --hparams='test_input_dir=wavs,N=$2'` and created wavs folder in the following directory `FastDiff/wavs/` but it returns the following error 
`| libtmux load error.
Traceback (most recent call last):
File "run", line 35, in <module>
set_hparams()
File "/content/drive/MyDrive/FastDiff_main/FastDiff/utils/hparams.py", line 96, in set_hparams
if v in ['True', 'False'] or type(config_node[k]) in [bool, list, dict]:
KeyError: 'test_input_dir'`
is there anything wrong in the command?

**Comment by Rongjiehuang** [comment]
Hi, pwg has been attached. Please try to add`test_input_dir` key in the config file.
