### ISSUE TITLE
cannot import name 'waveglow' from 'vocoders'

### ISSUE THREAD

**Issue by peyyman** [Rongjiehuang/FastDiff#15]
Hi,
It seems that some vocoder wrappers missed in the "vocoders" directory. They are imported in the "vocoders/\__init\__.py" but they are not in the vocoders directory.

Here is the traceback after running binarization step : 

```
Traceback (most recent call last):
  File "data_gen/tts/bin/binarize.py", line 23, in <module>
    binarize()
  File "data_gen/tts/bin/binarize.py", line 16, in binarize
    binarizer_cls = getattr(importlib.import_module(pkg), cls_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/payman/TTS/FastDiff/data_gen/tts/vocoder_binarizer.py", line 18, in <module>
    from vocoders.base_vocoder import get_vocoder_cls
  File "/home/payman/TTS/FastDiff/vocoders/__init__.py", line 2, in <module>
    from vocoders import waveglow
ImportError: cannot import name 'waveglow' from 'vocoders' (/home/payman/TTS/FastDiff/vocoders/__init__.py)
```

**Comment by peyyman** [comment]
I've seen that this issue resolved in the latest commit.
